all:
	xelatex Spectral-Methods
	bibtex Spectral-Methods
	xelatex Spectral-Methods
	xelatex Spectral-Methods

clean:
	rm Spectral-Methods-blx.bib
	rm Spectral-Methods.aux
	rm Spectral-Methods.bbl
	rm Spectral-Methods.blg
	rm Spectral-Methods.log
	rm Spectral-Methods.out
	rm Spectral-Methods.run.xml
	rm Spectral-Methods.toc