all:
	xelatex report-wenchong-Oct-2023
	bibtex report-wenchong-Oct-2023
	xelatex report-wenchong-Oct-2023
	xelatex report-wenchong-Oct-2023

clean:
	rm report-wenchong-Oct-2023-blx.bib
	rm report-wenchong-Oct-2023.aux
	rm report-wenchong-Oct-2023.bbl
	rm report-wenchong-Oct-2023.blg
	rm report-wenchong-Oct-2023.log
	rm report-wenchong-Oct-2023.out
	rm report-wenchong-Oct-2023.run.xml
	rm report-wenchong-Oct-2023.toc
